database:
  url: ${DATABASE_URL:jdbc:h2:mem://prod:MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
  username: ${DATABASE_USERNAME:sa}
  password: ${DATABASE_PASSWORD:}
  jpa_show_sql: true
  jpa_defer_datasource_initialization: false
  hibernate_ddl_auto: none
  hibernate_dialect: ${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}
  driver_class_name: ${DATABASE_DRIVER_CLASS_NAME:org.h2.Driver}

web-server:
  port: ${SERVER_PORT:8081}
  context_path: ${SERVER_CONTEXT_PATH:/dev-sync/api}
  undertow_threads_worker: 32
  undertow_threads_io: 2

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}

log:
  level_root: ${LOG_LEVEL_ROOT:INFO}

# Spring config override for dev environment.
spring:
  h2:
    console:
      enabled: true
      path: /h2
